apiVersion: v1
data:
  wordpress_db_password: cGFzc3dvcmQ=
  mysql_password: cGFzc3dvcmQ=
  mysql_random_root_password: cm9vdA==
kind: Secret
metadata:
  name: app-wordpress-secret
  namespace: wordpress
type: Opaque